# Generated by Django 4.0.6 on 2022-08-20 11:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
    ]
